In [1]:
###CONDUCT DATA ACCESS AND PROFILING###
##Importing and read doc
import pandas as pd
file_path = "/Users/haoranzhu/Downloads/Passengers_Satisfaction_Survey (2).csv"
df = pd.read_csv(file_path)
df.head()

/var/folders/33/ldfgcqdd5mn3kmrph8j1lm240000gn/T/ipykernel_70578/3196082834.py:5: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Food and drink,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Satisfaction
0,Male,Loyal Customer,69.0,Personal Travel,Business,32.0,3.0,2.0,3,5,1.0,1,3.0,14.0,0.0,Dissatisfied
1,Male,Disloyal Customer,20.0,Business travel,Eco,0.0,3.0,3.0,3,2,10.0,4,2.0,0.0,0.0,dissatisfied
2,Male,Disloyal Customer,41.0,Business travel,Business,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neutral
3,Male,Loyal Customer,52.0,Business travel,Business,0.0,2.0,4.0,4,1,2.0,2,4.0,0.0,6.0,Dissatisfied
4,Female,Disloyal Customer,21.0,Business travel,Business,0.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neutral

In [2]:
##Understand shape of the overall data 
df.shape

(104910, 16)

In [3]:
#Subset Data Frame Business Class
df_Business = df[df['Class'] == 'Business'].copy()
##Display First Rows
df_Business.head()

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Food and drink,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Satisfaction
0,Male,Loyal Customer,69.0,Personal Travel,Business,32.0,3.0,2.0,3,5,1.0,1,3.0,14.0,0.0,Dissatisfied
2,Male,Disloyal Customer,41.0,Business travel,Business,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neutral
3,Male,Loyal Customer,52.0,Business travel,Business,0.0,2.0,4.0,4,1,2.0,2,4.0,0.0,6.0,Dissatisfied
4,Female,Disloyal Customer,21.0,Business travel,Business,0.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neutral
5,Female,Loyal Customer,57.0,Business travel,Business,0.0,3.0,4.0,4,5,2.0,3,2.0,0.0,0.0,Dissatisfied

In [4]:
##Display Rows and Columns
df_Business.shape

(50000, 16)

In [5]:
##Columns Names and Data Types 
df_Business.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 0 to 104909
Data columns (total 16 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gender                             48239 non-null  object
 1   Customer Type                      48239 non-null  object
 2   Age                                47373 non-null  float64
 3   Type of Travel                     48239 non-null  object
 4   Class                              50000 non-null  object
 5   Flight Distance                    46604 non-null  float64
 6   Inflight wifi service              48239 non-null  float64
 7   Departure/Arrival time convenient  48239 non-null  float64
 8   Ease of Online booking             42705 non-null  object
 9   Food and drink                     42705 non-null  object
 10  Inflight entertainment             43649 non-null  float64
 11  Baggage handling                   43649 non-null  object
 12  Cleanliness                        43649 non-null  float64
 13  Departure Delay in Minutes         43649 non-null  float64
 14  Arrival Delay in Minutes           42098 non-null  object
 15  Satisfaction                       47840 non-null  object
dtypes: float64(7), object(9)
memory usage: 6.5+ MB

In [6]:
##Unique Values (Loop)
cols=df_Business.columns

for col in cols:
    print(col)
    unique=df_Business[col].unique()
    print(unique,'\n*\n\n')

Gender
['Male' 'Female' 'F' 'M' nan 'Fe male']
*


Customer Type
['Loyal Customer' 'Disloyal Customer' nan 'disloyal' 'Loyal']
*


Age
[ 69.  41.  52.  21.  57.  45.  39.  33.  10.  55.  59.  53.  56.  47.
  54.  25.  51.  60.  27.  43.  20.  19.  63.  50.  nan  38.  46.  85.
  26.  42.  30.  24.  22.  17.  48.  40.  16.  32.  35.  44.  49.  65.
  67.  66.  64.   7.  37.  36.  15.  62.  34.   0.  68.  70.  58.  11.
  74.  13.  80.  75.   9.  61.  71.  12.  73.  72.  18.  79.   8.  76.
  14.  77.  78. 180. 185.]
*


Type of Travel
['Personal Travel' 'Business travel' 'Business' nan]
*


Class
['Business']
*


Flight Distance
[3.200e+01 0.000e+00 5.600e+01 ... 4.983e+03 2.820e+06 9.000e+06]
*


Inflight wifi service
[ 3.  1.  2.  4.  0.  5. nan]
*


Departure/Arrival time convenient
[ 2.  1.  4.  0.  5.  3. nan]
*


Ease of Online booking
['3' nan '4' '0' '5' 'Unknown' '2' '1']
*


Food and drink
['5' nan '1' '3' 'Great' '4' '2' '0']
*


Inflight entertainment
[ 1. nan  2.  3.  4.  5. 10.  0.]
*


Baggage handling
['1' nan '2' '3' '5' '4' 'A']
*


Cleanliness
[ 3. nan  4.  2.  5.  0.]
*


Departure Delay in Minutes
[ 1.400e+01        nan  0.000e+00 -2.000e+00  1.000e+01  3.600e+01
  9.000e+00  3.500e+01  7.000e+00  1.100e+01  6.100e+01  2.000e+01
  1.160e+02  2.600e+01  1.300e+01  5.000e+01  7.100e+01  2.700e+01
  2.500e+01  6.000e+00  1.500e+01  3.200e+01  1.130e+02  1.000e+00
  3.000e+00  4.600e+01  4.200e+01  2.100e+01  4.300e+01  1.140e+02
  3.400e+01  2.300e+01  8.000e+00  5.000e+00  4.900e+01  7.600e+01
  3.700e+01  2.900e+01  1.340e+02  2.800e+01  1.900e+01  5.700e+01
  6.400e+01  2.000e+00  4.550e+02  1.230e+02  1.220e+02  4.000e+00
  1.010e+02  3.100e+01  3.900e+01  1.400e+02  8.900e+01  4.000e+01
  1.800e+01  2.400e+01  2.200e+01  1.110e+02  1.630e+02  9.300e+01
  1.600e+01  3.000e+01  4.700e+01  6.300e+01  1.700e+01  8.400e+01
  6.500e+01  4.500e+01  6.000e+01  7.700e+01  1.200e+01  3.800e+01
  1.610e+02  8.000e+01  7.400e+01  1.560e+02  3.300e+01  1.050e+02
  9.500e+01  8.800e+01  1.260e+02  1.950e+02  9.400e+01  4.800e+01
  1.060e+02  2.490e+02  7.800e+01  9.600e+01  7.200e+01  1.040e+02
  1.070e+02  1.720e+02  1.360e+02  4.400e+01  9.800e+01  8.700e+01
  9.100e+01  3.300e+02  5.800e+01  7.000e+01  1.250e+02  1.350e+02
  3.240e+02  6.800e+01  5.300e+01  1.200e+02  5.500e+01  5.900e+01
  9.700e+01  1.490e+02  5.200e+01  1.180e+02  5.600e+01  8.200e+01
  1.080e+02  1.520e+02  6.200e+01  2.100e+02  1.570e+02  5.400e+01
  1.470e+02  8.300e+01  1.380e+02  1.420e+02  1.280e+02  4.100e+01
  1.240e+02  2.000e+02  2.210e+02  8.100e+01  8.500e+01  1.100e+02
  7.300e+01  2.620e+02  6.600e+01  2.650e+02  8.600e+01  1.670e+02
  5.100e+01  1.580e+02  2.060e+02  1.680e+02  1.210e+02  2.420e+02
  1.990e+02  6.900e+01  6.700e+01  2.090e+02  1.410e+02  1.620e+02
  9.900e+01  7.500e+01  1.700e+02  1.830e+02  1.480e+02  4.020e+02
  1.800e+02  2.530e+02  1.510e+02  1.270e+02  2.520e+02  1.120e+02
  3.280e+02  1.840e+02  1.910e+02  7.900e+01  2.040e+02  2.550e+02
  2.820e+02  1.170e+02  2.400e+02  1.430e+02  1.590e+02  1.870e+02
  1.320e+02  1.000e+02  1.640e+02  2.380e+02  2.980e+02  1.850e+02
  2.760e+02  9.200e+01  1.710e+02  1.290e+02  1.190e+02  2.010e+02
  1.740e+02  6.920e+02  1.460e+02  1.780e+02  1.150e+02  1.540e+02
  9.000e+01  1.530e+02  1.370e+02  1.970e+02  1.750e+02  1.300e+02
  1.440e+02  1.960e+02  2.580e+02  2.270e+02  1.020e+02  2.030e+02
  3.590e+02  2.440e+02  1.900e+02  1.090e+02  3.260e+02  3.210e+02
  1.500e+02  3.510e+02  2.450e+02  2.720e+02  1.810e+02  2.110e+02
  2.160e+02  3.470e+02  1.310e+02  1.450e+02  3.830e+02  9.210e+02
  1.600e+02  1.660e+02  1.860e+02  1.650e+02  2.050e+02  3.360e+02
  1.930e+02  1.730e+02  4.300e+02  2.350e+02  1.820e+02  1.790e+02
  1.880e+02  2.740e+02  4.010e+02  1.940e+02  3.530e+02  2.190e+02
  3.030e+02  2.970e+02  1.030e+02  2.410e+02  2.120e+02  1.920e+02
  2.140e+02  2.330e+02  2.070e+02  1.390e+02  4.350e+02  1.330e+02
  6.100e+02  2.790e+02  3.100e+02  2.080e+02  3.060e+02  2.240e+02
  3.680e+02  2.480e+02  1.550e+02  2.590e+02  2.660e+02  3.380e+02
  2.670e+02  2.910e+02  2.180e+02  3.180e+02  2.150e+02  2.710e+02
  2.930e+02  2.130e+02  2.690e+02  2.850e+02  3.090e+02  4.520e+02
  3.220e+02  2.320e+02  4.230e+02  3.940e+02  2.920e+02  1.760e+02
  2.230e+02  2.860e+02  2.750e+02  3.330e+02  1.690e+02  2.460e+02
  2.730e+02  2.390e+02  4.800e+02  3.810e+02  3.020e+02  8.590e+02
  2.260e+02  2.900e+02  5.030e+02  1.890e+02  2.360e+02  1.770e+02
  3.420e+02  1.980e+02  3.070e+02  2.020e+02  2.640e+02  3.700e+02
  1.017e+03  4.650e+02  2.810e+02  4.630e+02  2.250e+02  9.330e+02
  3.170e+02  4.100e+02  4.070e+02  2.940e+02  3.570e+02  2.870e+02
  9.300e+02  3.040e+02  3.480e+02  3.400e+02  4.440e+02  2.770e+02
  4.290e+02  2.500e+02  3.190e+02  3.120e+02  3.130e+02  3.880e+02
  2.680e+02  4.150e+02  4.540e+02  3.920e+02  1.305e+03  2.290e+02
  2.200e+02  2.430e+02  4.500e+02  3.500e+02  2.220e+02  3.340e+02
  2.990e+02  2.170e+02  3.080e+02  3.440e+02  3.200e+02  5.010e+02
  4.380e+02  3.520e+02  3.580e+02  2.560e+02  2.600e+02  3.410e+02
  3.310e+02  2.890e+02  3.710e+02  2.280e+02  8.530e+02]
*


Arrival Delay in Minutes
[0.0 nan 6.0 21.0 12.0 16.0 8.0 49.0 36.0 65.0 10.0 107.0 103.0 9.0 18.0
 43.0 -45.0 66.0 25.0 13.0 24.0 105.0 14.0 7.0 57.0 29.0 39.0 120.0 63.0
 27.0 3.0 22.0 28.0 1.0 59.0 2.0 70.0 4.0 30.0 19.0 15.0 129.0 44.0 52.0
 210.0 124.0 119.0 5.0 42.0 33.0 98.0 34.0 31.0 48.0 156.0 84.0 20.0 46.0
 53.0 121.0 110.0 17.0 157.0 87.0 38.0 40.0 99.0 32.0 55.0 69.0 41.0 83.0
 67.0 96.0 60.0 45.0 78.0 26.0 23.0 37.0 171.0 71.0 81.0 168.0 80.0 35.0
 89.0 11.0 85.0 200.0 73.0 93.0 64.0 104.0 50.0 248.0 122.0 117.0 97.0
 163.0 135.0 146.0 140.0 68.0 72.0 128.0 348.0 77.0 134.0 94.0 133.0 323.0
 115.0 74.0 58.0 91.0 177.0 125.0 138.0 206.0 100.0 54.0 259.0 75.0 161.0
 137.0 131.0 233.0 217.0 130.0 142.0 101.0 154.0 256.0 112.0 47.0 62.0
 260.0 194.0 209.0 118.0 92.0 228.0 79.0 150.0 188.0 76.0 153.0 139.0 90.0
 246.0 95.0 61.0 203.0 143.0 158.0 174.0 187.0 56.0 51.0 389.0 106.0 257.0
 169.0 224.0 195.0 275.0 88.0 109.0 330.0 180.0 173.0 86.0 113.0 136.0
 202.0 255.0 305.0 225.0 82.0 148.0 116.0 186.0 126.0 204.0 287.0 181.0
 147.0 176.0 293.0 208.0 159.0 127.0 702.0 185.0 167.0 102.0 123.0 165.0
 182.0 295.0 152.0 191.0 164.0 218.0 262.0 268.0 108.0 379.0 193.0 240.0
 366.0 192.0 172.0 360.0 336.0 298.0 230.0 267.0 149.0 114.0 132.0 141.0
 183.0 196.0 231.0 359.0 229.0 386.0 924.0 213.0 266.0 145.0 216.0 151.0
 235.0 327.0 178.0 160.0 232.0 438.0 243.0 170.0 263.0 404.0 284.0 249.0
 198.0 302.0 290.0 184.0 227.0 212.0 162.0 223.0 470.0 155.0 593.0 309.0
 299.0 307.0 357.0 261.0 219.0 304.0 199.0 292.0 175.0 301.0 254.0 111.0
 258.0 253.0 270.0 265.0 '0' '16' '10' '4' '3' '9' '-45' '2' '14' '36'
 '260' '12' '42' '1' '31' '5' '6' '26' '13' '7' '11' '37' '132' '54' '27'
 '30' '35' '60' '22' '34' '8' '119' '63' '51' '45' '62' '116' '39' '81'
 '103' '92' '15' '24' '285' '84' '19' '141' '129' '73' '67' '55' '29' '28'
 '163' '18' '146' '91' '49' '117' '17' '53' '195' '44' '32' '40' '98'
 '130' '43' '193' '111' '75' '69' '250' '74' '115' '23' '302' '20' '21'
 '101' '33' '50' '99' '25' '180' '41' '444' '299' '142' '56' '159' '65'
 '57' '46' '38' '47' '134' '72' '48' '128' '90' '219' '126' '52' '88' '97'
 '136' '82' '59' '58' '64' '181' '403' '125' '407' '76' '334' '109' '147'
 '66' '80' '79' '68' '110' '331' '265' '83' '175' '78' '255' '108' '120'
 '70' '123' '100' '107' '167' '87' '157' '262' '186' '231' '145' '89'
 '102' '168' '118' '61' '148' '153' '96' '247' '158' '246' '104' '162'
 '264' '121' '114' '210' '133' '127' '131' '139' '169' '234' '85' '176'
 '93' '212' '86' '194' '137' '140' '105' '221' '277' '164' '173' '380'
 '160' '189' '217' '251' '206' '106' '200' '235' '171' '308' '270' '238'
 '113' '203' '122' '252' '150' '224' '165' '185' '471' '77' '112' '71'
 '177' '95' '151' '124' '436' '178' '319' '174' '860' '228' '135' '278'
 '317' '507' '94' '243' '143' '166' '385' '191' '205' '323' '149' '202'
 '222' '1011' '154' '493' '208' '307' '155' '503' '204' '298' '281' '152'
 '337' '213' '161' '920' '287' '144' '179' '258' '324' '237' '272' '182'
 '435' '409' '283' '284' '330' '362' '289' '952' '288' '190' '300' '321'
 '156' '341' '198' '201' '434' '392' '417' '271' '172' '295' '320' '9..'
 '223' 'Three' '256' '236' '209' '410' '187' '183' '170' '502' '381'
 '1280' '257' '211' '138' '297' '244' '470' '192' '327' '388' '242' '318'
 244.0 297.0 370.0 207.0 383.0 313.0 179.0 226.0 331.0 272.0 320.0 197.0
 144.0 393.0 500.0 242.0 322.0 190.0 335.0 471.0 274.0 214.0 220.0 250.0
 245.0 279.0 189.0 334.0 300.0 166.0 285.0 296.0 339.0 316.0 823.0]
*


Satisfaction
['Dissatisfied' 'neutral' 'satisfied' 'dissatisfied' nan '0' '1']
*

In [7]:
##Missing Values
df_Business.isna().sum()

Gender                               1761
Customer Type                        1761
Age                                  2627
Type of Travel                       1761
Class                                   0
Flight Distance                      3396
Inflight wifi service                1761
Departure/Arrival time convenient    1761
Ease of Online booking               7295
Food and drink                       7295
Inflight entertainment               6351
Baggage handling                     6351
Cleanliness                          6351
Departure Delay in Minutes           6351
Arrival Delay in Minutes             7902
Satisfaction                         2160
dtype: int64

In [8]:
##SummaryStatistics
df_Business.describe(include='all')

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Food and drink,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Satisfaction
count,48239,48239,47373.000000,48239,50000,4.660400e+04,48239.000000,48239.000000,42705,42705,43649.000000,43649,43649.000000,43649.000000,42098.0,47840
unique,5,4,NaN,3,1,NaN,NaN,NaN,7,7,NaN,6,NaN,NaN,608.0,6
top,Female,Loyal Customer,NaN,Business travel,Business,NaN,NaN,NaN,3,4,NaN,4,NaN,NaN,0.0,satisfied
freq,23000,40770,NaN,44063,50000,NaN,NaN,NaN,8635,10890,NaN,17056,NaN,NaN,12777.0,30398
mean,NaN,NaN,41.853186,NaN,NaN,1.934729e+03,2.774519,2.910695,NaN,NaN,3.835391,NaN,3.737520,13.595363,NaN,NaN
std,NaN,NaN,13.730683,NaN,NaN,4.369344e+04,1.423917,1.501711,NaN,NaN,1.233508,NaN,0.987664,36.595048,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,-5.421000e+03,0.000000,0.000000,NaN,NaN,0.000000,NaN,0.000000,-2.000000,NaN,NaN
25%,NaN,NaN,34.000000,NaN,NaN,5.940000e+02,2.000000,2.000000,NaN,NaN,3.000000,NaN,3.000000,0.000000,NaN,NaN
50%,NaN,NaN,43.000000,NaN,NaN,1.597000e+03,3.000000,3.000000,NaN,NaN,4.000000,NaN,4.000000,0.000000,NaN,NaN
75%,NaN,NaN,52.000000,NaN,NaN,2.565000e+03,4.000000,4.000000,NaN,NaN,5.000000,NaN,5.000000,10.000000,NaN,NaN
max,NaN,NaN,185.000000,NaN,NaN,9.000000e+06,5.000000,5.000000,NaN,NaN,10.000000,NaN,5.000000,1305.000000,NaN,NaN

In [9]:
##Frequency Distribution
for col in cols:
    print(f"\nColumn: {col}")
    print(df_Business[col].value_counts(dropna=False))
    print("-" * 40)

Column: Gender
Gender
Female     23000
Male       22830
NaN         1761
F           1361
M           1047
Fe male        1
Name: count, dtype: int64
----------------------------------------

Column: Customer Type
Customer Type
Loyal Customer       40770
Disloyal Customer     6636
NaN                   1761
disloyal               831
Loyal                    2
Name: count, dtype: int64
----------------------------------------

Column: Age
Age
NaN      2627
39.0     1935
40.0     1677
41.0     1533
42.0     1514
         ...
73.0       22
78.0       17
85.0       14
180.0       1
185.0       1
Name: count, Length: 75, dtype: int64
----------------------------------------

Column: Type of Travel
Type of Travel
Business travel    44063
Business            2122
Personal Travel     2054
NaN                 1761
Name: count, dtype: int64
----------------------------------------

Column: Class
Class
Business    50000
Name: count, dtype: int64
----------------------------------------

Column: Flight Distance
Flight Distance
NaN          3396
337.0         225
2475.0        187
2586.0        148
404.0         133
             ...
1285.0          1
1287.0          1
1288.0          1
1289.0          1
9000000.0       1
Name: count, Length: 3575, dtype: int64
----------------------------------------

Column: Inflight wifi service
Inflight wifi service
2.0    10784
3.0    10593
4.0     9140
1.0     8808
5.0     7025
0.0     1889
NaN     1761
Name: count, dtype: int64
----------------------------------------

Column: Departure/Arrival time convenient
Departure/Arrival time convenient
4.0    9993
3.0    9220
2.0    9183
5.0    9173
1.0    8546
0.0    2124
NaN    1761
Name: count, dtype: int64
----------------------------------------

Column: Ease of Online booking
Ease of Online booking
3          8635
4          8627
2          8444
5          7713
NaN        7295
1          7042
0          1747
Unknown     497
Name: count, dtype: int64
----------------------------------------

Column: Food and drink
Food and drink
4        10890
5        10296
3         9710
2         9567
NaN       7295
1         1722
Great      497
0           23
Name: count, dtype: int64
----------------------------------------

Column: Inflight entertainment
Inflight entertainment
4.0     15884
5.0     13508
3.0      6772
NaN      6351
2.0      5714
1.0      1451
10.0      314
0.0         6
Name: count, dtype: int64
----------------------------------------

Column: Baggage handling
Baggage handling
4      17056
5      14375
NaN     6351
3       5841
2       3783
1       1920
A        674
Name: count, dtype: int64
----------------------------------------

Column: Cleanliness
Cleanliness
4.0    14132
3.0    12473
5.0    11704
NaN     6351
2.0     5336
0.0        4
Name: count, dtype: int64
----------------------------------------

Column: Departure Delay in Minutes
Departure Delay in Minutes
0.0      24351
NaN       6351
10.0      1401
1.0       1228
2.0        917
         ...
239.0        1
273.0        1
333.0        1
347.0        1
853.0        1
Name: count, Length: 359, dtype: int64
----------------------------------------

Column: Arrival Delay in Minutes
Arrival Delay in Minutes
0.0      12777
0        11452
NaN       7902
1.0        474
2.0        463
         ...
246          1
323.0        1
277          1
348.0        1
823.0        1
Name: count, Length: 609, dtype: int64
----------------------------------------

Column: Satisfaction
Satisfaction
satisfied       30398
Dissatisfied     7794
neutral          6123
dissatisfied     3522
NaN              2160
1                   2
0                   1
Name: count, dtype: int64
----------------------------------------

In [10]:
##Duplicated Data Rows
df_Business.duplicated().sum()

np.int64(3064)

## Annotations of the Issues Data Presented ##

### **Data Issues Identified Before Cleansing** ###

**1. Inconsistent Column Names**  
Some columns include spaces and capital letters (e.g., “Customer Type”), which can cause errors in referencing column names during analysis.

**2. Inconsistent Categorical Values**  
- *Gender:* Includes inconsistent entries such as “F”, “M”, and “Fe male”.  
- *Customer Type:* Variants like “Loyal Customer”, “Disloyal Customer”, and “disloyal” need to be standardized.  
- *Type of Travel:* Contains “Business travel”, “Personal Travel”, and “Business”.

**3. Outliers and Invalid Numeric Data**  
- *Age:* Includes unrealistic values like 7 and 185.  
- *Flight Distance:* Contains extreme outliers (e.g., 2,820,000 and 9,000,000).

**4. Improper Rating Scales**  
Rating columns (Inflight WiFi Service, Cleanliness, etc.) contain text entries like “Great” and invalid values like 0 or 10.  
The valid range should be **1–5**.

**5. Mixed Data Types**  
Some numeric columns are stored as objects due to the presence of text or symbols.

**6. Missing Values (NaN)**  
Several columns, including *Ease of Online Booking*, *Food and Drink*, *Inflight Entertainment*, *Baggage Handling*, *Cleanliness*, and *Age*, have missing values.

**7. Duplicated Data**  
The dataset contains 3,864 duplicated rows, which must be removed to prevent bias.

**8. Ambiguous Satisfaction Labels**  
The *Satisfaction* column contains inconsistent values such as “satisfied”, “Satisfied”, “neutral”, and numeric codes like 0 and 1, requiring standardization.

In [11]:
###CONDUCT DATA CLEANSING###
##Verify df_Business Columns
for col in df_Business.columns:
    print(repr(col))

'Gender'
'Customer Type'
'Age'
'Type of Travel'
'Class'
'Flight Distance'
'Inflight wifi service'
'Departure/Arrival time convenient'
'Ease of Online booking'
'Food and drink'
'Inflight entertainment'
'Baggage handling'
'Cleanliness'
'Departure Delay in Minutes'
'Arrival Delay in Minutes'
'Satisfaction'

In [12]:
##Verify columns from the original Database
for c in df.columns: print(repr(c))

'Gender'
'Customer Type'
'Age'
'Type of Travel'
'Class'
'Flight Distance'
'Inflight wifi service'
'Departure/Arrival time convenient'
'Ease of Online booking'
'Food and drink'
'Inflight entertainment'
'Baggage handling'
'Cleanliness'
'Departure Delay in Minutes'
'Arrival Delay in Minutes'
'Satisfaction'

In [13]:
##Drop 'Class' Column
df_Business = df_Business.drop(columns=['Class'], errors='ignore')

In [14]:
#Verify column was dropped
df_Business.columns

Index(['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Flight Distance',
       'Inflight wifi service', 'Departure/Arrival time convenient',
       'Ease of Online booking', 'Food and drink', 'Inflight entertainment',
       'Baggage handling', 'Cleanliness', 'Departure Delay in Minutes',
       'Arrival Delay in Minutes', 'Satisfaction'],
      dtype='object')

In [15]:
##Rename Columns in Lowercase and Remove Space and Replace it with _
df_Business.rename(columns = lambda x: x.lower().replace(' ','_'), inplace= True)
df_Business.columns

Index(['gender', 'customer_type', 'age', 'type_of_travel', 'flight_distance',
       'inflight_wifi_service', 'departure/arrival_time_convenient',
       'ease_of_online_booking', 'food_and_drink', 'inflight_entertainment',
       'baggage_handling', 'cleanliness', 'departure_delay_in_minutes',
       'arrival_delay_in_minutes', 'satisfaction'],
      dtype='object')

In [16]:
##Modify Improperly Formatted Data and Handle Bad Data
#Column 1 'Gender' - Standardized abbreviations ("F"/"M") and spacing issues ("Fe male") to "Female"/"Male"
df_Business['gender'] = df_Business['gender'].astype(str).str.strip()
df_Business['gender'] = df_Business['gender'].replace({
    'F':'Female','M':'Male','Fe male':'Female'})

In [17]:
df_Business['gender'].unique()

array(['Male', 'Female', 'nan'], dtype=object)

In [18]:
#Column 2 'customer_type' - Unified similar categories ("Loyal Customer"/"Disloyal Customer"/"disloyal") into "Loyal"/"Disloyal"
df_Business['customer_type'] = df_Business['customer_type'].replace({
    'Loyal Customer':'Loyal',
    'Disloyal Customer':'Disloyal',
    'disloyal':'Disloyal'})

In [19]:
df_Business['customer_type'].unique()

array(['Loyal', 'Disloyal', nan], dtype=object)

In [20]:
import numpy as np

In [21]:
#Column 3 'age' - Ensuring age fits a reasonable range 
df_Business.loc[~df_Business['age'].between(12, 90), 'age'] = np.nan

In [22]:
df_Business['age'].unique()

array([69., 41., 52., 21., 57., 45., 39., 33., nan, 55., 59., 53., 56.,
       47., 54., 25., 51., 60., 27., 43., 20., 19., 63., 50., 38., 46.,
       85., 26., 42., 30., 24., 22., 17., 48., 40., 16., 32., 35., 44.,
       49., 65., 67., 66., 64., 37., 36., 15., 62., 34., 68., 70., 58.,
       74., 13., 80., 75., 61., 71., 12., 73., 72., 18., 79., 76., 14.,
       77., 78.])

In [23]:
#Column 4 'type_of_travel' - Standardized travel categories ("Business"-"Business Travel") for naming consistency 
df_Business['type_of_travel'] = df_Business['type_of_travel'].replace({
    'Business':'Business travel',
    'Personal Travel':'Personal Travel'})

In [24]:
df_Business['type_of_travel'].unique()

array(['Personal Travel', 'Business travel', nan], dtype=object)

In [25]:
#Column 5 'flight_distance' - Get rid of outiers in flight distance 
df_Business.loc[df_Business['flight_distance'] <= 0, 'flight_distance'] = np.nan
lo, hi = df_Business['flight_distance'].quantile([0.01, 0.99])
df_Business['flight_distance'] = df_Business['flight_distance'].clip(lo, hi)

In [26]:
df_Business['flight_distance'].unique()

array([ 116.,   nan,  118., ..., 3942., 3943., 3944.])

In [27]:
#Columns 6-13 - Rate ordinal values (0-5) 
rating_rest = [
    'inflight_wifi_service',
    'departure/arrival_time_convenient',
    'ease_of_online_booking',
    'food_and_drink',
    'inflight_entertainment',
    'baggage_handling',
    'cleanliness'
]

rating_rest = [c for c in rating_rest if c in df_Business.columns]

for c in rating_rest:
    df_Business[c] = pd.to_numeric(df_Business[c], errors='coerce')
    df_Business.loc[~df_Business[c].between(0, 5), c] = np.nan

In [28]:
#Columns 6-13 - Adjust rating scale from 0-5 to 1-5; converting 0 to NaN
rating_cols = [
    'inflight_wifi_service',
    'departure/arrival_time_convenient',
    'ease_of_online_booking',
    'food_and_drink',
    'inflight_entertainment',
    'baggage_handling',
    'cleanliness'
]


for c in rating_cols:
    df_Business[c] = pd.to_numeric(df_Business[c], errors='coerce')
    df_Business.loc[(df_Business[c] == 0) | (~df_Business[c].between(1, 5)), c] = np.nan

In [29]:
###Check the corect columns were cleaned   
rating_rest

['inflight_wifi_service',
 'departure/arrival_time_convenient',
 'ease_of_online_booking',
 'food_and_drink',
 'inflight_entertainment',
 'baggage_handling',
 'cleanliness']

In [30]:
###Check each cleaned columns unique values; to make sure no out-of-range values
for c in rating_rest:
    print(f"\n{c} unique values:")
    print(sorted(df_Business[c].dropna().unique()))

inflight_wifi_service unique values:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]

departure/arrival_time_convenient unique values:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]

ease_of_online_booking unique values:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]

food_and_drink unique values:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]

inflight_entertainment unique values:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]

baggage_handling unique values:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]

cleanliness unique values:
[np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]

In [31]:
###Check how many missing values were created after cleaning
df_Business[rating_rest].isna().sum()

inflight_wifi_service                3650
departure/arrival_time_convenient    3885
ease_of_online_booking               9539
food_and_drink                       7815
inflight_entertainment               6671
baggage_handling                     7025
cleanliness                          6355
dtype: int64

In [32]:
###Confirm numeric Integrity - min (1) max (5); Show a descriptive summary of the cleaned columns
df_Business[rating_rest].describe()

,inflight_wifi_service,departure/arrival_time_convenient,ease_of_online_booking,food_and_drink,inflight_entertainment,baggage_handling,cleanliness
count,46350.000000,46115.000000,40461.000000,42185.000000,43329.000000,42975.000000,43645.000000
mean,2.887594,3.044758,3.037691,3.437857,3.791248,3.888493,3.737862
std,1.335533,1.396714,1.370849,1.196997,1.119549,1.101006,0.987061
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000
50%,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000
75%,4.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [33]:
#Column 14 'departure_delay_in_minutes'- Convert into numbers, convert value less then zero into NaN, get rid of extreme value
for c in ['departure_delay_in_minutes', 'arrival_delay_in_minutes']:
    df_Business[c] = pd.to_numeric(df_Business[c], errors='coerce')
    df_Business.loc[df_Business[c] < 0, c] = np.nan
    lo, hi = df_Business[c].quantile([0.01, 0.99])
    df_Business[c] = df_Business[c].clip(lo, hi)

In [34]:
###Verify result 
df_Business[['departure_delay_in_minutes', 'arrival_delay_in_minutes']].describe()

       departure_delay_in_minutes  arrival_delay_in_minutes
count                43152.000000              41422.000000
mean                    12.899866                 13.114263
std                     29.186623                 30.093039
min                      0.000000                  0.000000
25%                      0.000000                  0.000000
50%                      0.000000                  0.000000
75%                     11.000000                 11.000000
max                    172.000000                177.000000

In [35]:
#Column 15 'Satisfaction' - Reconstruct the label 
df_Business['satisfaction'] = (
        df_Business['satisfaction']
          .replace({'satisfied':'Satisfied',
                    'dissatisfied':'Dissatisfied',
                    'neutral':'Neutral',
                    '1':'Satisfied',
                    '0':'Dissatisfied'}))

In [36]:
##Verify the Output
df_Business['satisfaction'].unique()

array(['Dissatisfied', 'Neutral', 'Satisfied', nan], dtype=object)

In [37]:
##Handle Missing Values
#Categorical Values - Fill with 'Unknown'
for col in ['customer_type', 'type_of_travel', 'gender']:
    if col in df_Business.columns:
        df_Business[col] = df_Business[col].fillna('Unknown')

In [38]:
#Continuos Numeric Values - Fill with median
for col in ['age', 'flight_distance']:
    if col in df_Business.columns:
        df_Business[col] = df_Business[col].fillna(df_Business[col].median())

In [39]:
#Rating Columns (0-5) - Fill with mode
rating_cols = [
    'inflight_wifi_service',
    'departure/arrival_time_convenient',
    'ease_of_online_booking',
    'food_and_drink',
    'inflight_entertainment',
    'baggage_handling',
    'cleanliness'
]
rating_cols = [c for c in rating_cols if c in df_Business.columns]

for col in rating_cols:
    mode_val = df_Business[col].mode(dropna=True).iat[0]
    df_Business[col] = df_Business[col].fillna(mode_val)

In [40]:
#Delay Columns - Fill with median 
for col in ['departure_delay_in_minutes', 'arrival_delay_in_minutes']:
    if col in df_Business.columns:
        df_Business[col] = df_Business[col].fillna(df_Business[col].median())

In [41]:
#Satisfaction - Fill with "Unknown"
if 'satisfaction' in df_Business.columns:
    df_Business['satisfaction'] = df_Business['satisfaction'].fillna('Unknown')

In [42]:
##Verify that no missing values remain 
print(df_Business.isna().sum().sort_values(ascending=False).head(10))
print("Total NA:", int(df_Business.isna().sum().sum()))

gender                               0
customer_type                        0
age                                  0
type_of_travel                       0
flight_distance                      0
inflight_wifi_service                0
departure/arrival_time_convenient    0
ease_of_online_booking               0
food_and_drink                       0
inflight_entertainment               0
dtype: int64
Total NA: 0

In [43]:
##Remove fully duplicated observations
df_Business = df_Business.drop_duplicates()

In [44]:
#Verify
print("Duplicates after drop:", df_Business.duplicated().sum())
print("Final row count:", len(df_Business))

Duplicates after drop: 0
Final row count: 46864

In [45]:
##Fix Column Datatypes
#Convert rating columns from object to float
cols_to_float = ['ease_of_online_booking', 'food_and_drink', 'baggage_handling']
for col in cols_to_float:
    if col in df_Business.columns:
        df_Business[col] = df_Business[col].astype(float)

In [46]:
#Convert categorical values to category dtype
cat_cols = ['gender', 'customer_type', 'type_of_travel', 'satisfaction']
for col in cat_cols:
    if col in df_Business.columns:
        df_Business[col] = df_Business[col].astype('category')

In [47]:
#Verify Datatypes
df_Business.dtypes

gender                               category
customer_type                        category
age                                   float64
type_of_travel                       category
flight_distance                       float64
inflight_wifi_service                 float64
departure/arrival_time_convenient     float64
ease_of_online_booking                float64
food_and_drink                        float64
inflight_entertainment                float64
baggage_handling                      float64
cleanliness                           float64
departure_delay_in_minutes            float64
arrival_delay_in_minutes              float64
satisfaction                         category
dtype: object

## Final Annotations — Comparing the Data Before and After Cleansing 

The original dataset went through multiple data cleansing processes to ensure **consistency, accuracy, and readiness for analysis**.

---

### **Summary of Column Changes**

**Gender**  
Originally stored as text (`object`) with inconsistent entries such as “Fe male”, “M”, and “F”. These were standardized to “Male” and “Female”, converted to categorical type, and all missing values were filled with **'Unknown'**.

**Customer_Type**  
Contained mixed formats (“Loyal Customer”, “Disloyal”, and lowercase variants). Categories were unified into **“Loyal”** and **“Disloyal”**, datatype converted to categorical, and missing values filled with **'Unknown'**.

**Age**  
Contained out-of-range values (7 and 185) and some missing entries. Values outside the realistic range (12–90) were replaced with NaN, then filled with the **median age**. Datatype remained numeric (`float`).

**Type_of_Travel**  
Included inconsistent categories (“Business”, “Business travel”) and missing data. These were standardized to **“Business travel”** and **“Personal Travel”**, converted to categorical, and missing values replaced with **'Unknown'**.

**Flight_Distance**  
Contained extreme outliers and missing values. Outliers were capped within the **1st and 99th percentiles**, datatype preserved as numeric (`float`), and missing entries filled with the **median**.

**Inflight_Wifi_Service**  
Originally numeric but included values outside the 1–5 range. Values were restricted to valid ratings (**1–5**), converted to numeric, and missing values filled with the **mode**.

**Departure/Arrival_Time_Convenient**  
Contained out-of-range and missing values. All values were limited to the **1–5 range**, datatype set to `float`, and missing entries replaced with the **mode**.

**Ease_of_Online_Booking**  
Read as object type due to text and “Unknown” entries. Converted to `float`, cleaned of non-numeric values, restricted to **1–5 range**, and filled with the **mode**.

**Food_and_Drink**  
Contained text entries like “Great” and numeric strings. Converted to numeric, restricted to the **1–5 range**, and missing values filled with the **mode**.

**Inflight_Entertainment**  
Included invalid ratings (e.g., 10) and missing values. Out-of-range values were replaced with NaN, restricted to **1–5**, datatype set to `float`, and missing entries filled with the **mode**.

**Baggage_Handling**  
Contained invalid entry “A” and some missing values. Converted to `float`, invalid entries replaced with NaN, restricted to **1–5**, and missing data filled with the **mode**.

**Cleanliness**  
Numeric but with some missing entries and minor inconsistencies. Restricted to the **1–5 range**, missing values filled with **mode**, and datatype kept as `float`.

**Departure_Delay_in_Minutes**  
Included negative and extreme delay times. Converted to numeric, negative values replaced with NaN, outliers capped within the **1st–99th percentile range**, and missing entries filled with the **median**.

**Arrival_Delay_in_Minutes**  
Similar to departure delay, negative and extreme values were cleaned, datatype converted to `float`, and missing entries replaced with the **median**.

**Satisfaction**  
Contained inconsistent labels (“1”, “0”, “satisfied”, “neutral”) and missing values. All categories standardized to **“Satisfied”**, **“Dissatisfied”**, and **“Neutral”**, datatype changed to categorical, and missing entries filled with the **most frequent label**.

**Class**  
This column was dropped as it was no longer needed for analysis.

---

### **Post-Cleansing Summary**

After cleansing, all columns are standardized to their correct datatypes, inconsistent entries were corrected, and **no missing values remain in the dataset**.  
The data is now **clean, consistent, and ready for analysis**.
**Overall Comparison Summary:**  
The data cleansing process successfully improved dataset quality by eliminating inconsistencies, correcting data types, and handling missing values. Compared to the original dataset, the cleaned version is fully standardized, reliable, and ready for analytical modeling.

In [48]:
df_Business.to_csv('cleaned_data.csv', index=False)

In [49]:
import os
os.getcwd()

'/Users/haoranzhu/Downloads'

In [50]:
os.listdir()

['overcoming-two-issues-that-are-sinking-gen-ai-programs_final-4.pdf',
 'I20_Zhu_Haoran_N0031423284_Post-completion OPT I-20 for USCIS Submission.pdf',
 'BrattleGroup_CoverLetter_LeoZhu.docx',
 'Resume_ Leo Zhu.docx',
 'Leo_Zhu_JPM_Cover_Letter.docx',
 'OperaSetup.zip',
 'MISM6202_05a_Probability_Fundamentals.pdf',
 'bain-report__midyear-private-equity-2025-4.pdf',
 '_______________.csv',
 'Resume_ Leo Zhu-3.pdf',
 'googlechrome.dmg',
 'CBRE_Investment_Internship_Cover_Letter.docx',
 'MS_in_Business_Analytics_Fact_Sheet-8.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-33.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-27.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-4.pdf',
 'the-state-of-fashion-beauty-june-2025-6.pdf',
 '截屏2025-09-23 17.40.17.png',
 'Leo Zhu-resume.pdf',
 'Module 8 - Lab - Cross Validation.R',
 'the-state-of-fashion-beauty-june-2025-7.pdf',
 'Exam_1_Reviewing_Sheet.docx',
 'item-m40903334663-92001902004365300206573377-2023-12-18 2.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-5.pdf',
 'MISM6202_02_Data_Management.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-26.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-32.pdf',
 'Data Wrangling Project 2.ipynb',
 'MS_in_Business_Analytics_Fact_Sheet-9.pdf',
 'Recommendation_Letter_Haoran_Leo_Zhu_Northeastern_Aug6.pdf',
 'Questions_for_Landlord.docx',
 'Resume_ Leo Zhu-2.pdf',
 'MAPFRE_Cover_Letter_Haoran_Zhu.docx',
 'bain-report__midyear-private-equity-2025-5.pdf',
 'reconfiguring-work-change-management-in-the-age-of-gen-ai_final.pdf',
 'Advertising.csv',
 'transforming-employer-health-benefits-large-employers-activist-role.pdf',
 'Customers.csv',
 'overcoming-two-issues-that-are-sinking-gen-ai-programs_final-5.pdf',
 'overcoming-two-issues-that-are-sinking-gen-ai-programs_final-7.pdf',
 'https:www.mckinsey.com:~:media:mckinsey:industries:consumer%20packaged%20goods:our%20insights:future%20of%20wellness%20trends:the-2-trillion-dollar-global-wellness-market-gets-a-millennial-and-gen-z-glow-up_final.pdf?shouldIndex=false.pdf',
 'Kearney_General_Cover_Letter.docx',
 'JLDB_Build.sql_副本',
 'Cover_Letter_Leo_Zhu_Updated.docx',
 'Ch2_Q55_V13_Data_File.xlsx',
 'Haoran Zhu - Sales - Independent Contractor Offer Letter template.docx.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-24.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-30.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-18.pdf',
 'HSG_CoverLetter_LeoZhu.docx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-7.pdf',
 'Oracle 12c SQL - Chapter 1 Overview of Database Concepts.ppt',
 'Ch06_Q25_Data_File_v16 (1).xlsx',
 'the-state-of-fashion-beauty-june-2025-5.pdf',
 'jpg-to-word.doc',
 'the-state-of-fashion-beauty-june-2025-4.pdf',
 'Income.xlsx',
 'MISM6205.rdp',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-6.pdf',
 'document-0.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-19.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-31.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-25.pdf',
 'Passengers_Satisfaction_Survey.csv',
 'Cover%20letter.pdf.pdf',
 'Oracle SQL - Chapter 4 Constraints.ppt',
 'Ch3_Q13_V15_Data_File.xlsx',
 'Midterm Study Guide.pdf',
 'VISA 2.pdf',
 'overcoming-two-issues-that-are-sinking-gen-ai-programs_final-6.pdf',
 'Networking_Tracker_LeoZhu_Updated-2.xlsx',
 'WritingSample_LeoZhu_ManattHealth.docx',
 'Exam1_CheatSheet.pdf',
 'Commonwealth Cover Letter.pdf',
 'overcoming-two-issues-that-are-sinking-gen-ai-programs_final-2.pdf',
 'rides.xlsx',
 'ch6-1-example-start.R',
 'Resume_ Leo Zhu-4 (1).pdf',
 'M06-Lab-model-evaluation.R',
 'Analysis_Group_Cover_Letter.docx',
 'bain-report__midyear-private-equity-2025-2.pdf',
 'what-is-infrastructure_final.pdf',
 'Resume_LeoZhu_Justified.docx',
 'networking_tracker_cn.xlsx',
 'Oracle SQL - Chapter 11 Group Functions - Ans.pptx',
 'ManattHealth_CoverLetter_LeoZhu.docx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-21.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-35.pdf',
 'Connect Canvas Deep Integration Registration.pptx',
 'Resume_LeoZhu_OnePage_With_Summary.docx',
 '.DS_Store',
 'W9.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-2.pdf',
 'Data Wrangling Project 2 (2).ipynb',
 'Ch01_Q19_Data_File.xlsx',
 'Oracle SQL -Chapter 9 Joining Data from Multiple Tables.ppt',
 'Oracle SQL - Chapter 8 Restricting Rows and Sorting Data.ppt',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-3.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-34.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-20.pdf',
 '截屏2025-05-28 22.36.29.pdf',
 'item-m40903334663-92001902004365300206573377-2023-12-18.pdf',
 'Menusifu - NDA.pdf',
 'bain-report__midyear-private-equity-2025-3.pdf',
 'Resume_ Leo Zhu-4.pdf',
 'CRA_CoverLetter_LeoZhu.docx',
 'Kearney_PERL_Cover_Letter.docx',
 'overcoming-two-issues-that-are-sinking-gen-ai-programs_final-3.pdf',
 '截屏2025-09-23 17.40.17 (1).png',
 'certificate.pdf',
 'Networking_Tracker_LeoZhu.xlsx',
 'Personal Statement.pdf',
 'Decimal_Health_Cover_Letter_Leo_Zhu.docx',
 'Recommendation letter.docx',
 'Leo_Zhu_Cover_Letter_MJ_Insurance.docx',
 'Safari.pdf',
 'Oracle SQL - Chapter 10 Selected Single-Row Functions - Ans.ppt',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-36.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-22.pdf',
 'Leo_Zhu_CRA_LifeSciences_Intern_Cover_Letter.docx',
 'MISM6202_03_Summary_Measures.pdf',
 'Resume_ Leo Zhu(6:7).docx',
 'Leo Zhu-resume 2.pdf',
 'the-state-of-fashion-beauty-june-2025-3.pdf',
 'the-state-of-fashion-beauty-june-2025-2.pdf',
 'GCC_Constitution_08.31.18.docx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-23.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-37.pdf',
 'IQVIA_Cover_Letter_HaoranZhu.docx',
 '.localized',
 'MS_in_Business_Analytics_Fact_Sheet.pdf',
 'Untitled document.pdf',
 'CV_Haoran Zhu (1).pdf',
 'bain-report__midyear-private-equity-2025.pdf',
 'state_Connecticut.pdf',
 'Leo_Zhu_Teneo_Cover_Letter.pdf',
 'creating-a-thriving-chemical-semiconductor-supply-chain-in-america.pdf',
 'Untitled.ipynb',
 'BeautifulSoup Functions - Example-1.ipynb',
 'TemporaryId-283845-638264448000000000.pdf',
 '~$ABtest.xlsx',
 'what-are-glp-1-medications-2.pdf',
 'MSBA_Regression_Midterm_Cheat_Sheet.pdf',
 'Fall_Semester_Budget_with_Loan_Tracking.csv',
 'CharlesRiver_CoverLetter_LeoZhu_Strategy.docx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-50.pdf',
 'QralGroup_CoverLetter_LeoZhu.docx',
 'Leo_Zhu_Cover_Letter_RSAdvisors.docx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-44.pdf',
 'ECG_CoverLetter_LeoZhu.docx',
 'Resume_ Leo Zhu_1.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-78.pdf',
 'Letter.pdf',
 'VISA.pdf',
 'CeD.24SO-FF11-HAU7.pdf',
 'Haoran_Zhu_Rockefeller_Cover_Letter.docx',
 'MSBA_Regression_Midterm_Cheat_Sheet_v2 (1).pdf',
 'what-are-glp-1-medications.pdf',
 'I-94 Official Website - Get Most Recent I-94 Response.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-79.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-45.pdf',
 'Enrollment-283845-638264448000000000.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-51.pdf',
 '3d9d46c7-e612-4252-b162-6ea4a63cc641.ipynb',
 'Leo Zhu.docx',
 'OperaGXSetup.zip',
 'https:www.mckinsey.com:~:media:mckinsey:industries:consumer%20packaged%20goods:our%20insights:state%20of%20beauty:2025:the-state-of-fashion-beauty-june-2025.pdf?shouldIndex=false.pdf',
 'what-are-glp-1-medications-3.pdf',
 'black_friday_test.csv',
 'Leo_Zhu_Cover_Letter_Altman_Solon.pdf',
 'Logistic Regression.pdf',
 'reservation_an1874651138.ics',
 'Passengers_Satisfaction_Survey (2).csv',
 'Networking_Tracker_LeoZhu_Updated_v2.xlsx',
 'Example - Data Enrichment and Trasformation',
 'the-state-of-fashion-beauty-june-2025-19.pdf',
 'BADigitalExercisePrepGuide (1).pdf',
 'CV_Haoran Zhu (6).pdf',
 'presentation-2.ics',
 'FILE.pdf',
 'Atlas-and-national-coffee-shops-final.pdf',
 'Article 2.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-47.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-53.pdf',
 'Leo_Zhu_Teneo_Cover_Letter.docx',
 'SSR_TSRPT-2.pdf',
 'what-is-micromobility.pdf',
 'Resume_ Leo Zhu (4)-2.pdf',
 'Exam1_CheatSheet_v3.docx',
 'OOS_Perm_Conv_0-205-399-184.pdf',
 'Letter 2.pdf',
 '1-Form-First-Race-and-Ethnicity-Form-Haoran-Zhu.pdf',
 'Rippling_Agentic_AI_Opportunity.docx',
 'SSR_TSRPT-3.pdf',
 'the-state-of-fashion-beauty-june-2025.pdf',
 'baa10k.xlsx',
 'JLDB_Build.sql',
 'rewiring-pharmas-regulatory-submissions-with-ai-and-zero-based-design_final.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-52.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-46.pdf',
 'federal-2.pdf',
 'ABtest.xlsx',
 'Example - Data Enrichment and Trasformation-1.zip',
 'LoanApprovalDisclosure.pdf',
 'ch6-1-example-complete.R',
 '2025-09-BLUE-MOON-MOVE-IN-Katherine-Aquino-4-100760-signed',
 'the-state-of-fashion-beauty-june-2025-18.pdf',
 'ADL_CoverLetter_LeoZhu.docx',
 'Recommendation_Letter_Haoran_Leo_Zhu_Final_Cleaned.docx',
 'Leo_Zhu_Cover_Letter_Alton.docx',
 'the-state-of-fashion-beauty-june-2025-20.pdf',
 'Ch3_Q21_Data_File.xlsx',
 'LP79AEE1864-2_副本.pdf',
 'RStudio-2025.05.1-513.dmg',
 'Ch06_Q25_Data_File_v16.xlsx',
 'rides.csv',
 'what-are-glp-1-medications-4.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-81.pdf',
 'IMG_8361.pdf',
 'Module 3 - Lab - Linear Regression.R',
 'cleaned_data.csv',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-42.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-56.pdf',
 'Risk_Checklist_Bilingual.docx',
 'SSR_TSRPT-7.pdf',
 'Leo_Zhu_CRA_Cover_Letter.docx',
 'bain_brief_accelerating_mission_critical_teams_in_pharma.pdf',
 'HR-Employee - Profiling _ Cleansing.ipynb',
 'SSR_TSRPT-6.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-57.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-43.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-80.pdf',
 'M5 - Regression Extensions.pdf',
 'Questions_for_Landlord_Full.docx',
 'Irm Investment Cover.pdf',
 'CV_Haoran Zhu (7).pdf',
 'the-speed-to-market-imperative-for-life-sciences-capital-delivery-v3.pdf',
 'M6 - Model Evaluation.pdf',
 'Leaning Into the Turbulence: Private Equity Midyear Report 2025 | Bain & Company.pdf',
 'Haoran Zhu_cover letter.pdf',
 'the-state-of-fashion-beauty-june-2025-21.pdf',
 'Ch2_Q25_V10_Data_File.xlsx',
 'andrei-kurylovich-andrei-kurylovich-shot-2-v6-artstation.jpg',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-82.pdf',
 'Graduate Student Honor Code.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-69.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-55.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-41.pdf',
 'HaoranZhu_FinancialSupport.pdf',
 'Letter-3.pdf',
 'optimizing-healthcare-supply-costs-from-the-physicians-perspective-v3.pdf',
 'SSR_TSRPT-4.pdf',
 'LeoZhu_ForceFactor_CoverLetter.docx',
 'Leo_Zhu_SimonKucher_CoverLetter.pdf',
 'SSR_TSRPT-5.pdf',
 'Letter-2.pdf',
 'MSBA_Regression_Midterm_Cheat_Sheet_v2 (1)_副本.pdf',
 'Module 8 - Lab - Cross Validation (1).R',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-40.pdf',
 'Leo_Zhu_Cover_Letter_CornerStone.pdf',
 'Rental_Risk_Minimization_Checklist_EN_CN.xlsx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-54.pdf',
 'Heat-550.cap',
 'CRI_CoverLetter_LeoZhu.docx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-68.pdf',
 'CrossHarbor_CoverLetter_LeoZhu.docx',
 'Career_Fair_Battle_Sheet_Leo_Zhu.pdf',
 'Ch3_Q3_V19_Data_File.xlsx',
 'document-0_副本.pdf',
 'HealthAdvances_CoverLetter_LeoZhu.docx',
 'Leo_Zhu_Career_Fair_Action_Plan.pdf',
 'Letter_merged.pdf',
 'Data Wrangling Project 2 (4).ipynb',
 'Resume_ Leo Zhu_02 (2).pdf',
 'I-94:I-95 Official Website - Get Most Recent Response.pdf',
 'the-state-of-fashion-beauty-june-2025-13.pdf',
 'SSR_TSRPT-11.pdf',
 'MS_in_Business_Analytics_Fact_Sheet-12.pdf',
 'Personal statement (2).pdf',
 'Module 4 - Lab - Logistic Regression.R',
 'item-m34248813360-92001902004365300206267634-2023-12-17.pdf',
 'House_price (1).csv',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-71.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-65.pdf',
 'Resume_%20Leo%20Zhu.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-59.pdf',
 'Resume_Leo_Zhu_SummaryFormatted_Final.docx',
 'SSR_TSRPT-8.pdf',
 'Data Profiling & Cleansing_With Data.zip',
 'EconicPartners_CoverLetter_LeoZhu_Clean.docx',
 'Ch6_Q60_Data_File.xlsx',
 'Cover_Letter_Leo_Zhu.docx',
 'Connect Access Code and Purchase FAQ.pdf',
 'SSR_TSRPT-9.pdf',
 'Leo_Zhu_Deloitte_Cover_Letter.docx',
 'the-2-trillion-dollar-global-wellness-market-gets-a-millennial-and-gen-z-glow-up_final.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-58.pdf',
 'CV_Haoran English.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-64.pdf',
 'LoanPacket.png',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-70.pdf',
 'Resume_ Leo Zhu_02.pdf',
 'Rental_Risk_Minimization_Checklist__EN___CN_.csv',
 'Data Wrangling Project 2 (1).ipynb',
 'MISM6202_06a_Sampling_Distributions.pdf',
 'fica.pdf',
 'MicrosoftTeams.pkg',
 'Resume_ Leo Zhu_02 (1).pdf',
 'MS_in_Business_Analytics_Fact_Sheet-13.pdf',
 'SSR_TSRPT-10.pdf',
 'the-state-of-fashion-beauty-june-2025-12.pdf',
 'the-state-of-fashion-beauty-june-2025-10.pdf',
 'PROJECT.pdf',
 '朱浩然-简历-0721.pdf',
 'state_Massachusetts.pdf',
 'SSR_TSRPT-12.pdf',
 'MS-Business-Analytics_Curriculum_2020-4.pdf',
 'MS_in_Business_Analytics_Fact_Sheet-11.pdf',
 'Monthly_Budget_with_Loan_Balance_Tracking.csv',
 'insurance_ma.pdf',
 'Recommendation_Letter_Haoran_Leo_Zhu_Verizon.docx',
 'LoanPacket.pdf',
 'Auto_副本.csv',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-66.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-72.pdf',
 'Teradyne_CoverLetter_LeoZhu.docx',
 '【20】Spring 2022 ECNU Course List_Upperclassmen（2020级）.xlsx',
 'OOS_Perm_Conv_0-205-399-184-1.pdf',
 'MISM6202_06c_Hypothesis_Testing.pdf',
 'Ch2_Q29_V02_Data_File.xlsx',
 'Class 7 Exercise_Black Friday email campaign optimization.pdf',
 'reconfiguring-work-change-management-in-the-age-of-gen-ai_final-2.pdf',
 'Data Profiling & Cleansing_With Data (1).zip',
 'SSR_TSRPT.pdf',
 'Leo_Zhu_Cover_Letter_Health_Advances.docx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-73.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-67.pdf',
 'Hands on – Restaurant Data-1',
 'state.pdf',
 'Resume_ Leo Zhu.pdf',
 'HaoranZhu_Rental_Income_Explanation.docx',
 'MS_in_Business_Analytics_Fact_Sheet-10.pdf',
 'MS-Business-Analytics_Curriculum_2020-5.pdf',
 'Redstone_WritingSample_LeoZhu_LONG.docx',
 'SSR_TSRPT-13.pdf',
 'workshop (1).ics',
 'the-state-of-fashion-beauty-june-2025-11.pdf',
 'the-state-of-fashion-beauty-june-2025-15.pdf',
 'CV_Haoran Zhu.pdf',
 'Career_Management_Toolkit_All_Programs.pdf',
 'MS_in_Business_Analytics_Fact_Sheet-14.pdf',
 'Updated_Networking_Interaction_Tracker.csv',
 'Updated_Shared_Household_Budget__Full_Amount_.csv',
 'Maryville_CoverLetter_LeoZhu.docx',
 'LEK_Cover_Letter_Leo_Zhu.docx',
 'MA-TB-Risk-Assessment-1.pdf',
 'Linear Regression 01.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-63.pdf',
 'Redstone_WritingSample_LeoZhu.docx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-77.pdf',
 '1-Form-CITY-OF-BOSTON-NOTICE-OF-TENANT-S-RIGHTS-AND-RESOURCES-Lease-9-15-2025-to-9-14-2026.pdf',
 'LP79AEE1864.pdf',
 'Resume Academic Tech Update.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-76.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-62.pdf',
 'Midterm Study Guide (1).pdf',
 'Ch3_Q17_V12_Data_File.xlsx',
 'Transfer-in-form-for-F1-students-111616.pdf',
 'Ch6_Q55_V20_Data_File (1).xlsx',
 'MISM 6205 Syllabus FL 25-1.pdf',
 'Shared_Household_Budget__Full_Amount_.csv',
 'KxAdvisors_CoverLetter_LeoZhu.docx',
 'cbae76e4-b11f-45e9-b8cf-ad7c7c23c924.pdf',
 'state_Massachusetts-2.pdf',
 'MS_in_Business_Analytics_Fact_Sheet-15.pdf',
 'NU Health Report 24-25 Final 2.0 (002).pdf',
 'Data Profiling & Cleansing',
 'RxSense_CoverLetter_LeoZhu.docx',
 'the-state-of-fashion-beauty-june-2025-14.pdf',
 'Career_Fair_Battle_Sheet_Leo_Zhu_v2.pdf',
 'the-next-specialty-the-physician-ceo_final.pdf',
 'SSR_TSRPT-14.pdf',
 'marketing_analysis.R',
 'the-state-of-fashion-beauty-june-2025-16.pdf',
 'Loomis_Sayles_Cover_Letter_Leo_Zhu.docx',
 'Resume_ Leo Zhu (4).pdf',
 'MS-Business-Analytics_Curriculum_2020-2.pdf',
 'Resume_Anonymous_OC%26C.pdf',
 'MSBA_Regression_Midterm_Cheat_Sheet_Final.pdf',
 'Flagship_CoverLetter_LeoZhu.docx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-48.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-74.pdf',
 'MS-Business-Analytics_Curriculum_2020.pdf',
 'Zoom.pkg',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-60.pdf',
 'CabotProperties_CoverLetter_LeoZhu.docx',
 'the-state-of-aviation-2025-final.pdf',
 'Monthly_Budget_Breakdown__Fall_Semester_.csv',
 'wt_launcher_osx_1.0.3.47.dmg',
 'Siemens_CoverLetter_LeoZhu.docx',
 'Hayden_Associate_Consultant_Cover_Letter.docx',
 'Statement_of_Interest_Leo_Zhu.docx',
 'Doc2.docx',
 'Four New Trends Reinforce Medtech’s Core Playbook | Bain & Company.pdf',
 'MISM6202_06b_Estimation.pdf',
 'Resume_ Leo Zhu_1-2.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-61.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-75.pdf',
 'EconicPartners_CoverLetter_LeoZhu.docx',
 'Resume_Anonymous_OC%26C.docx',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-49.pdf',
 'Prompt Guide_Networking and Professional Branding.pdf',
 'Acclaim Testing Link 2025-08-11.pdf',
 'ElectronicDeliveryandConsent.html',
 'Leo Zhu cover letter.docx',
 'Data Wrangling Project 2 (3).ipynb',
 'Exam1_CheatSheet_v3_EN.docx',
 'MS-Business-Analytics_Curriculum_2020-3.pdf',
 'Project 01 Inventory DB  ERD.jpg',
 'EXAM 1 题目.docx',
 'the-state-of-fashion-beauty-june-2025-17.pdf',
 'mckinsey-technology-trends-outlook-2025.pdf',
 'Passengers_Satisfaction_Survey (1).csv',
 'Resume_Leo_Zhu.pdf',
 'class3-exercise.R',
 'download.html',
 'MISM6202_01_Introduction.pdf',
 'MISM6202_05b_Normal_Distribution.pdf',
 'Accelerating Mission-Critical Teams in Pharma | Bain & Company.pdf',
 'ZS_Lionel_Lobo_Networking_Record.xlsx',
 'Qvest_Cover_Letter.docx',
 'Leo_Zhu_Cover_Letter_Altman_Solon_Final.docx',
 '.ipynb_checkpoints',
 'federal.pdf',
 'BADigitalExercisePrepGuide.pdf',
 'the-evolution-of-commerce-media-navigating-a-new-era-in-advertising-12.pdf',
 'Vertical_Format__Monthly_Budget_with_Loan_Balance_Tracking.csv',
 'Success Team request.jpg',
 'CRA_LifeSciencesIntern_CoverLetter_LeoZhu.docx',
 'MinuteClinic Appointment.ics',